import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Nav } from "@/components/common/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="relative">
        {/* <div className="fixed inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"> */}
        <div className="fixed inset-0 -z-10 h-full w-full bg-white">
          {/* <div className="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-fuchsia-400 opacity-20 blur-[100px]"></div> */}
        </div>
        <Nav />
        <main className="mx-auto tracking-normal font-roboto">
          {/* <main className="max-w-[1200px] mx-auto tracking-normal font-roboto"> */}
          {children}
          <Toaster richColors />
        </main>
      </body>
    </html>
  );
}
