import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
const Nav = dynamic(() => import("@/components/common/Nav").then(mod => mod.Nav), {
  ssr: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="relative">
        <div className="fixed inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]">
          <div className="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-fuchsia-400 opacity-20 blur-[100px]"></div>
        </div>
        <header className="max-w-[1200px] w-full top-6 absolute left-1/2 transform -translate-x-1/2">
          <Nav />
        </header>
        <main className="max-w-[1200px] mx-auto py-36 min-h-dvh tracking-normal font-roboto">
          {children}
        </main>
      </body>
    </html>
  );
}
